

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE EXTENSION IF NOT EXISTS "pgsodium";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."fotos" (
    "id" bigint NOT NULL,
    "enlace" character varying NOT NULL
);


ALTER TABLE "public"."fotos" OWNER TO "postgres";


ALTER TABLE "public"."fotos" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Foto_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."productos" (
    "id" bigint NOT NULL,
    "nombre" character varying NOT NULL,
    "descripcion" character varying NOT NULL,
    "precio" bigint NOT NULL,
    "foto_id" bigint NOT NULL,
    "categoria_id" bigint NOT NULL
);


ALTER TABLE "public"."productos" OWNER TO "postgres";


ALTER TABLE "public"."productos" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Producto_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."categorias" (
    "id" bigint NOT NULL,
    "nombre" character varying NOT NULL
);


ALTER TABLE "public"."categorias" OWNER TO "postgres";


ALTER TABLE "public"."categorias" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."categoria_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."direcciones" (
    "id" bigint NOT NULL,
    "direccion" character varying NOT NULL,
    "numero" character varying,
    "indicaciones" character varying,
    "telefono" character varying NOT NULL,
    "id_usuario" "uuid" NOT NULL
);


ALTER TABLE "public"."direcciones" OWNER TO "postgres";


ALTER TABLE "public"."direcciones" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."direcciones_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."estados_pedido" (
    "id" bigint NOT NULL,
    "id_pedido" bigint NOT NULL,
    "estado" bigint NOT NULL,
    "fecha_entrega" timestamp without time zone
);


ALTER TABLE "public"."estados_pedido" OWNER TO "postgres";


ALTER TABLE "public"."estados_pedido" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."estado_pedido_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."pedidos" (
    "id" bigint NOT NULL,
    "cantidad" bigint NOT NULL,
    "fecha" timestamp without time zone NOT NULL,
    "id_direccion" bigint NOT NULL,
    "id_producto" bigint NOT NULL,
    "id_usuario" "uuid" NOT NULL
);


ALTER TABLE "public"."pedidos" OWNER TO "postgres";


ALTER TABLE "public"."pedidos" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."pedidos_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."reservas" (
    "id" bigint NOT NULL,
    "fecha" timestamp with time zone NOT NULL,
    "id_usuario" "uuid" NOT NULL
);


ALTER TABLE "public"."reservas" OWNER TO "postgres";


ALTER TABLE "public"."reservas" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."reservas_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."usuarios" (
    "id" "uuid" NOT NULL,
    "Nombre" character varying NOT NULL,
    "Apellido" character varying NOT NULL,
    "telefono" character varying NOT NULL
);


ALTER TABLE "public"."usuarios" OWNER TO "postgres";


ALTER TABLE ONLY "public"."fotos"
    ADD CONSTRAINT "Foto_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."productos"
    ADD CONSTRAINT "Producto_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."usuarios"
    ADD CONSTRAINT "Usuarios_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."categorias"
    ADD CONSTRAINT "categoria_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."direcciones"
    ADD CONSTRAINT "direcciones_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."estados_pedido"
    ADD CONSTRAINT "estado_pedido_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."estados_pedido"
    ADD CONSTRAINT "estados_pedido_pedido_id_key" UNIQUE ("id_pedido");



ALTER TABLE ONLY "public"."pedidos"
    ADD CONSTRAINT "pedidos_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."reservas"
    ADD CONSTRAINT "reservas_fecha_key" UNIQUE ("fecha");



ALTER TABLE ONLY "public"."reservas"
    ADD CONSTRAINT "reservas_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."usuarios"
    ADD CONSTRAINT "Usuarios_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."direcciones"
    ADD CONSTRAINT "direcciones_id_usuario_fkey" FOREIGN KEY ("id_usuario") REFERENCES "public"."usuarios"("id");



ALTER TABLE ONLY "public"."estados_pedido"
    ADD CONSTRAINT "estados_pedido_pedido_id_fkey" FOREIGN KEY ("id_pedido") REFERENCES "public"."pedidos"("id");



ALTER TABLE ONLY "public"."pedidos"
    ADD CONSTRAINT "pedidos_id_direccion_fkey" FOREIGN KEY ("id_direccion") REFERENCES "public"."direcciones"("id");



ALTER TABLE ONLY "public"."pedidos"
    ADD CONSTRAINT "pedidos_producto_id_fkey" FOREIGN KEY ("id_producto") REFERENCES "public"."productos"("id");



ALTER TABLE ONLY "public"."pedidos"
    ADD CONSTRAINT "pedidos_usuario_id_fkey" FOREIGN KEY ("id_usuario") REFERENCES "public"."usuarios"("id");



ALTER TABLE ONLY "public"."productos"
    ADD CONSTRAINT "producto_categoria_id_fkey" FOREIGN KEY ("categoria_id") REFERENCES "public"."categorias"("id");



ALTER TABLE ONLY "public"."productos"
    ADD CONSTRAINT "producto_foto_id_fkey" FOREIGN KEY ("foto_id") REFERENCES "public"."fotos"("id");



ALTER TABLE ONLY "public"."reservas"
    ADD CONSTRAINT "reservas_id_usuario_fkey" FOREIGN KEY ("id_usuario") REFERENCES "public"."usuarios"("id");



ALTER TABLE "public"."categorias" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."direcciones" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."estados_pedido" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."fotos" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."pedidos" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."productos" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."reservas" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."usuarios" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";



































































































































































































GRANT ALL ON TABLE "public"."fotos" TO "anon";
GRANT ALL ON TABLE "public"."fotos" TO "authenticated";
GRANT ALL ON TABLE "public"."fotos" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Foto_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Foto_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Foto_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."productos" TO "anon";
GRANT ALL ON TABLE "public"."productos" TO "authenticated";
GRANT ALL ON TABLE "public"."productos" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Producto_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Producto_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Producto_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."categorias" TO "anon";
GRANT ALL ON TABLE "public"."categorias" TO "authenticated";
GRANT ALL ON TABLE "public"."categorias" TO "service_role";



GRANT ALL ON SEQUENCE "public"."categoria_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."categoria_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."categoria_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."direcciones" TO "anon";
GRANT ALL ON TABLE "public"."direcciones" TO "authenticated";
GRANT ALL ON TABLE "public"."direcciones" TO "service_role";



GRANT ALL ON SEQUENCE "public"."direcciones_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."direcciones_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."direcciones_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."estados_pedido" TO "anon";
GRANT ALL ON TABLE "public"."estados_pedido" TO "authenticated";
GRANT ALL ON TABLE "public"."estados_pedido" TO "service_role";



GRANT ALL ON SEQUENCE "public"."estado_pedido_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."estado_pedido_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."estado_pedido_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."pedidos" TO "anon";
GRANT ALL ON TABLE "public"."pedidos" TO "authenticated";
GRANT ALL ON TABLE "public"."pedidos" TO "service_role";



GRANT ALL ON SEQUENCE "public"."pedidos_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."pedidos_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."pedidos_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."reservas" TO "anon";
GRANT ALL ON TABLE "public"."reservas" TO "authenticated";
GRANT ALL ON TABLE "public"."reservas" TO "service_role";



GRANT ALL ON SEQUENCE "public"."reservas_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."reservas_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."reservas_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."usuarios" TO "anon";
GRANT ALL ON TABLE "public"."usuarios" TO "authenticated";
GRANT ALL ON TABLE "public"."usuarios" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";






























RESET ALL;
